### ISSUE TITLE
pyinstaller chaos.spec not seeming to work on OS X

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit-bundler#2]
I am getting the following when I run `pyinstaller chaos.spec`

```
pyinstaller chaos.spec 
50 INFO: PyInstaller: 3.4
50 INFO: Python: 3.6.4
56 INFO: Platform: Darwin-17.7.0-x86_64-i386-64bit
60 INFO: UPX is not available.
Traceback (most recent call last):
  File "/Users/russellmiles/code/src/github.com/chaostoolkit/chaostoolkit-bundler/.bundler/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "/Users/russellmiles/code/src/github.com/chaostoolkit/chaostoolkit-bundler/.bundler/lib/python3.6/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/russellmiles/code/src/github.com/chaostoolkit/chaostoolkit-bundler/.bundler/lib/python3.6/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/russellmiles/code/src/github.com/chaostoolkit/chaostoolkit-bundler/.bundler/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/russellmiles/code/src/github.com/chaostoolkit/chaostoolkit-bundler/.bundler/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 29, in <module>
  File "/Users/russellmiles/code/src/github.com/chaostoolkit/chaostoolkit-bundler/.bundler/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 189, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script '<CHAOS_PATH>' not found
```

**Comment by russmiles** [comment]
This on OS X High Sierra
